### ISSUE TITLE
Non-findable sphinx tool package in requirements.txt

### ISSUE THREAD

**Issue by maaeli** [kif/freesas#23]
The requirements.txt currently lists sphinxcontrib-programoutputsetuptools

pip cannot find it (nor can I) and we don't seem to use it.

Am I missing something here? Or can it be removed?

**Comment by kif** [comment]
Most of the common parts are directly inherited (copy/pasted) from `silx`.
We are using this to include man-pages into the generateed the documentation. But it is possible this is not implemented (yet) into `freesas`. It should be declared in `doc/source/conf.py` but apparently we are not using it.

**Comment by kif** [comment]
I think there is typo there ...
