### ISSUE TITLE
pip install / build fails on windows

### ISSUE THREAD

**Issue by maaeli** [kif/freesas#7]
Hi,

I no longer can install freesas   (or to be more precise, supycomp) on Windows.  It might be same issue as described by Valentin here: https://github.com/pypa/setuptools/issues/694,,,

Cheers,
Martha

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c
 /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\brennich.pcdom3\appdata\local\conti
nuum\anaconda3\lib\site-packages\numpy\core\include -Ic:\users\brennich.pcdom3\a
ppdata\local\continuum\anaconda3\include -Ic:\users\brennich.pcdom3\appdata\loca
l\continuum\anaconda3\include -I"C:\Program Files (x86)\Microsoft Visual Studio
14.0\VC\INCLUDE" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\
ucrt" -I"C:\Program Files (x86)\Windows Kits\8.1\include\shared" -I"C:\Program F
iles (x86)\Windows Kits\8.1\include\um" -I"C:\Program Files (x86)\Windows Kits\8
.1\include\winrt" /Tcfreesas\_distance.c /Fobuild\temp.win-amd64-3.6\Release\fre
esas\_distance.obj /openmp
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe
/nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH
:c:\users\brennich.pcdom3\appdata\local\continuum\anaconda3\libs /LIBPATH:c:\use
rs\brennich.pcdom3\appdata\local\continuum\anaconda3\PCbuild\amd64 /LIBPATH:"C:\
Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" /LIBPATH:"C:\Prog
ram Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" /LIBPATH:"C:\Program
Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" /EXPORT:PyInit__distance build\
temp.win-amd64-3.6\Release\freesas\_distance.obj /OUT:build\lib.win-amd64-3.6\fr
eesas\_distance.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6\Release\free
sas\_distance.cp36-win_amd64.lib
  LINK : fatal error LNK1181: cannot open input file ' .obj'
  error: Command "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86
_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFES
TUAC:NO /LIBPATH:c:\users\brennich.pcdom3\appdata\local\continuum\anaconda3\libs
 /LIBPATH:c:\users\brennich.pcdom3\appdata\local\continuum\anaconda3\PCbuild\amd
64 /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" /
LIBPATH:"C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" /LIBP
ATH:"C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" /EXPORT:PyInit_
_distance build\temp.win-amd64-3.6\Release\freesas\_distance.obj /OUT:build\lib.
win-amd64-3.6\freesas\_distance.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-
3.6\Release\freesas\_distance.cp36-win_amd64.lib  " failed with exit status 1181

  ----------------------------------------
  Failed building wheel for freesas
  Running setup.py clean for freesas
Failed to build freesas
Installing collected packages: freesas
  Found existing installation: freesas 0.6.0
    Uninstalling freesas-0.6.0:
      Successfully uninstalled freesas-0.6.0
  Running setup.py install for freesas ... error
    Complete output from command c:\users\brennich.pcdom3\appdata\local\continuu
m\anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\B
RENNI~1.PCD\\AppData\\Local\\Temp\\pip-install-h4r71kou\\freesas\\setup.py';f=ge
tattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.cl
ose();exec(compile(code, __file__, 'exec'))" install --record C:\Users\BRENNI~1.
PCD\AppData\Local\Temp\pip-record-12t8tve9\install-record.txt --single-version-e
xternally-managed --compile:

**Comment by maaeli** [comment]
So the issue seems to be that the openmp flag adds `' '` to `extra_link_args `, which at least on my system leads to ` .obj` in the compiler arguments, resulting in exit code 1181. Replacing `' '` by `''` fixes this. As I could install freesas without problems in the past, I suspect it might be related to version changes in python libraries of msvc on my system and probably requires more testing.
Python: 3.6.0
Numpy 1.13.1
Cython 0.25.2
setuptools 27.2.0
msvc 14.0

**Comment by kif** [comment]
On Fri, 17 Aug 2018 05:34:17 -0700
maaeli <notifications@github.com> wrote:

> So the issue seems to be that the openmp flag adds `' '` to `extra_link_args `, which at least on my system leads to ` .obj` in the compiler arguments, resulting in exit code 1181. Replacing `' '` by `''` fixes this. As I could install freesas without problems in the past, I suspect it might be related to version changes in python libraries of msvc on my system and probably requires more testing.

I already faced issues with trailing spaces in compiler options.

Our reference project, *silx* is handling this ton of small details with much care. It would make sense to upgrade the build procedure using the same tools.

-- 
Jérôme Kieffer

**Comment by maaeli** [comment]
Hi,

I am all in favour of using the same build procedure as silx! 

Cheers,
Martha

**Comment by kif** [comment]
On Wed, 29 Aug 2018 00:39:23 -0700
maaeli <notifications@github.com> wrote:

> Hi,
> 
> I am all in favour of using the same build procedure as silx! 

work is ongoing in that direction...

-- 
Jérôme Kieffer
tel +33 476 882 445

**Comment by kif** [comment]
As the compilation procedure is the same as silx, it compiles and runs now on windows as well
