### ISSUE TITLE
pip install failed on Debian

### ISSUE THREAD

**Issue by maaeli** [kif/freesas#8]
Hi,

here is the error: Any idea about the reason?

Command "/user/brennich/mypython/environments/SAXSplots/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-_v2ulyig/freesas/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-7d41rp7n/install-record.txt --single-version-externally-managed --compile --install-headers /user/brennich/mypython/environments/SAXSplots/include/site/python3.4/freesas" failed with error code 1 in /tmp/pip-install-_v2ulyig/freesas/

Cheers,
Martha

**Comment by maaeli** [comment]
Hi,

so I figure out what's going on: On the computer I was using neither python-dev nor python3-dev were installed. I guess this issue only arose for freesas as the other packages have pre-built wheels...
Would it make sense to list this as requirement somewhere? 

Cheers,
Martha

**Comment by kif** [comment]
On Wed, 29 Aug 2018 00:42:32 -0700
maaeli <notifications@github.com> wrote:

> Hi,
> 
> so I figure out what's going on: On the computer I was using neither python-dev nor python3-dev were installed. I guess this issue only arose for freesas as the other packages have pre-built wheels...
> Would it make sense to list this as requirement somewhere? 

If we follow the *silx* way we will have to provide pseudo official
debian packages, which represents more work than the 4-line long script
we are currently using.

**Comment by kif** [comment]
should be fixed now with the v0.7.0
